# Generated by Django 5.1.4 on 2024-12-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('categoria', models.TextField(max_length=50)),
                ('codigo', models.CharField(max_length=5)),
                ('disponibilidade', models.BooleanField(default=True)),
            ],
        ),
    ]
