# Generated by Django 5.1.4 on 2025-01-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_catalogo_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('categoria', models.TextField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('codigo', models.CharField(max_length=5)),
                ('estoque', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Sobre',
        ),
    ]
