# Generated by Django 5.1.4 on 2025-01-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_produto_delete_contato_delete_sobre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalogo',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
