# Generated by Django 5.1.4 on 2025-01-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='catalogos/')),
                ('ativo', models.BooleanField(default=True)),
                ('produtos', models.ManyToManyField(to='produtos.produto')),
            ],
        ),
    ]
