# Generated by Django 5.1.4 on 2025-01-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(default='', upload_to='produtos/'),
            preserve_default=False,
        ),
    ]
