# Generated by Django 5.1.4 on 2025-01-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_vendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='descricao',
        ),
    ]
