# Generated by Django 5.1.4 on 2025-01-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_vendas_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='codigo',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
