# Generated by Django 5.1.4 on 2025-01-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_vendas_produtos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendas',
            new_name='Venda',
        ),
    ]
