# Generated by Django 5.1.4 on 2025-01-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_rename_vendas_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='preco',
        ),
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now_add=True),
        ),
    ]
