# Generated by Django 5.1.4 on 2025-01-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_remove_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
