# Generated by Django 5.1.4 on 2025-01-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_produto_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data_venda',
            new_name='data',
        ),
    ]
