# Generated by Django 5.1.4 on 2025-01-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_cliente_venda_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=600),
        ),
    ]
