# Generated by Django 5.1.4 on 2025-01-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
