# Generated by Django 5.1.4 on 2025-01-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_delete_produtos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendas',
        ),
    ]
